version: "3.9"

services:

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend_dist:/app/dist
    command: ["echo", "Frontend built"]

  backend:
    build:
      context: ./backend
    volumes:
      - frontend_dist:/app/dist   # récupère le dist du frontend
    ports:
      - "8000:8000"
    depends_on:
      - frontend

volumes:
  frontend_dist:
