version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"  # Port typique de Vite (ou change en 3000 si c'est React/Vue classique)
    # On lance le serveur de dev au lieu de copier les fichiers
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app # Pour que tes modifs de code soient prises en compte en direct
      - /app/node_modules # Pour éviter les conflits de dépendances

  backend:
    build:
      context: ./backend
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env    
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # Pour modifier le Python sans redémarrer le conteneur